theme: minima
title: CV
author: Author Noel Washington Black
description: Mr Noel Black.							Mobile: 07527281089 

Email: noel.black@outlook.com                                                       

          noelwblack@icloud.com	 

          uk.linkedin.com/pub/noel-black/59/b55/380/ 

PROFILE 

An adaptable Service-driven IT professional, Experienced and focused with strong insights and intuition. A Co-ordinated Problem Solver with a passion for IT and Technology. A Former Team Leader with broad industry experience that includes Media, Finance, Advertising, Legal and IT services. Able to set and achieve goals. Very client-focused and very committed. Can Absorb highly complex theories and materials, collected and analytical. Ability to work with all levels of the business, HP Desktop Laptop Mobile Devices Printer and Server Skilled, Experienced  in the Microsoft Windows environment with Microsoft Office, Active Directory, Windows XP, 7, 8,  Apple OSX and Unix, ITSM Experience, Citrix client set-up experience. Datacentre support and monitoring with Nagios. A very combined organised responsible Professional with an eye for detail. 

Major Achievements 

Promotion to Operations Team Leader for the Daily Mirror, Sunday Mirror and the Racing Post, responsibilities included the management of six Desktop Engineers and three Network Engineers. Supervising and Directing an number of 3rd and 4th line Specialist during problem Escalation and main point of contact and direction reporting directly to the IT Operations Manager and Newspaper Editors. 

Increased the SLA levels by implementing new call handling and call pick up procedures. 

Bringing about a fundamental change in the quality of service provided by team members.  

Created Trinity Mirrors Spare Parts process that successfully increased engineer’s performances and reduced cost. 

Created the Mirror’s IT disposal process and redefined process as and when required which saved money and vital floor space. 

Conducted annul PDR’s using SMART for each Team members and advising on training courses, of which some have now become Certified Engineers. 

Reducing costs and meeting SLA’s ROI’s by implementing software and hardware upgrades where necessary to bring in new technology and processes.  

Work Experience 

Dec 2010 to November 2013 | Desktop Support Team Leader (Project Leader for local Desktop Team) 

Trinity Mirror PLC | One Canada Square E15 5AP  

Managing Desktop support engineers during PC equipment roll out of windows XP to windows 7 migration using Altiris Ghost 7.1, and MSWDS. Setup-up new PC as per organizations procedure with data, mail accounts, mapped drives, and shared printers installed and tested to user satisfaction. 

Planning and delegating routine maintenance of Standard Desktop PC Image Using Altiris 7.1 MMC for departments so builds are up-to-date. 

Creating and Documenting PC build Process and procedures for departments and team members. 

Delegating priority calls, system responsibility’s and Jobs for support team members to Carrie out, as daily procedures require.  

Reviewing existing procedures for efficiency and cost. 

Coordinate with Business managers and users to ensure quick and timely out come to IT related issues to user satisfaction. 

Creating and Ensuring staff rota is up to date and IT department is available 24/7 365 days annually.  

Ensuring the company’s quality assurance procedure and ITIL’s best practices are implemented and followed by Team members.  

Supervise Large Scale Department PC desk moves with internal IT staff and external contractors delegating and coordinating until completion of project.          

Deployed IT equipment projects Configure and install network printers, FAX’s other networked related devices, Install print Drivers on Windows Print server, create shared network Print queues, share resources through Active directory group policies, Diagnose and repair TCPIP network related problems as well as subject matter expert for team.  

Run PC Software Inventory Reports using tools such as Altiris management console, Altiris Endpoint protection to gather Hardware and software information of PC’s remotely saving time and desk side visit   

Blackberry, IPhone, iPads, setup devices as per user with security, cerate user accounts, Sync Account with Devices, User Device Connectivity (public and private Wi-Fi, transfer contacts, Add to correct Active Directory Group, Coordinate with Business managers and users to ensure quick and timely role out.  

Subject Matter Expert for the Team focusing on Desktop support and Hardware diagnostic, software and Altiris administration, software deployment. 

The Planning and executing of PC and Peripherals moves Projects ensuring all required prerequisites are managed such as network Patch management, Phone, and power, communicated effetely throughout all departments and contractors achieving the desired outcome. 

Working with ITSM systems such as Front Range Heat Service Management within SLA times while updating all involved clear technical call updates and emails with a Business service management (BSM) approach to manage business-aligned IT services  

Support Mirror Desktop users with Microsoft Office and server based software applications, HP Sure Store Tape library backup and restore schedule, HP server support, and maintenance.  

Point of contact to third Line able to communicate take instructions from of site SME and carry out instructions to obtain the desired resolution of the incident, Document and pass on information.  

Use reports to review fault calls to improve performance and first time fix rate, to also reducing reacquiring incidents  processing helpdesk tickets, Manage Team Rota’s and Holiday request,  

Encouraging good business practices and leadership.  

May 2001to Dec 2010 | Operations Team Leader 

Trinity Mirror PLC | One Canada Square E15 5AP  Team Lead to five Desktop Operations Support Analyst engineers for second and 3rd line support. Repair Desktop PC Laptop and computer related incidents, Maintain Server Backup restores, Team management and responsible for end-to-end delivery and accountability of Technology Services to the consistent transmission of live data for Mirror newspaper business on a multitude of different clients and a variety of different IT architectures utilizing different skills. Working with Windows servers & applications within a mixed OS environment Windows XP, Websense software application 

Windows 7, Apple MAC, Microsoft office support, Unix Server, Networking, Datacenter support and monitoring with Nagios. HP server support, NetApp Share admin, SAN management and repair. KoFax Scanner system support, SAP Business objects software installs. Websense  

Duties: 

Lead a Team of 5 Engineers to deliver IT services to over 2000 users on site.     

Managed Rota and holiday request. 

Deploy Desktop software using Altiris MMC write create procedure for desktop team.  

Assist with the upgrade of WIN7 project.  

Use remote control tools to Diagnose and repair network and PC related problems,  

log incidents via phone, and email, use IT monitoring tools such as Nagios, 

Delegating Hardware disposal task and responsibilities to Engineers.  

Tech support and training to other desktop engineers. 

PC audit and software inventory  

Network Drive mapping and access 

March 2001 | Operations Support Analyst in the Operations Team 

Trinity Mirror PLC | One Canada Square E15 5AP 

Duties: 

Face to face and handling & prioritising problems of Windows XP, Windows server 2000, Apple MAC, Microsoft office, Unix Server, Networking  TCP/IP, Monitoring live feeds, Deploy Desktop Images using Altiris MMC. Deploy Desktop software using Altiris MMC. Use remote control tools to Diagnose and repair network and PC related problems. Log incidents via phone, and email, use IT monitoring tools, HP Server support, HP Desktop support, Active Directory share set-up. Citrix Thin client set-up and diagnostic, Network printer setup, PC Fault finding, Printer Fault finding, Compaq server fault finding, routine backups back-ups and Restores with DLT Library systems. Computer Hardware disposal. Mitel Telephone system Administration, Mitel Voice Mail Backup. Monitoring system infrastructure ensuring IT services are available. Ensure all team members comply with company’s security policy and procedures.  

April 1995 to May 2001  

GE Capital Information Technology Solutions, Greens Lane, Middlesex. (Computacenter FROM 2001). 

Installation Engineer 

System Installation engineer – in the Implementation Team. 

Field/Site Support 

Sites include Coutts, MCI WorldCom, Sainsbury’s, Prudential, GlaxoSmithKline, 

April 1995 to June 1993   

CMS, Huntingdon Business Centre, Blackstone Road, Huntingdon, Cambridgeshire, PE29 6EF. 

Computer Field Service Engineer. 

June 1993 to April 1995 

Precision Peripherals Ltd Unit 2, Home Farm Industrial Estate, Yattendon, Thatcham, RG18 0XT  
Senior Field Service Technician 

June 1991 to April 1992 

Ricoh Ltd Unit 2, Industrial Estate,  
Field Service Technician 

Education 

[Westminster Technical College] |City Guilds 223 microcomputer technology part I, Part II 

[South East London Boys School] CSE’s | Electronics, Math’s, English, Science.  

PROFESSIONAL	 

Microsoft Windows Server 2000 MCP. 

Trinity Mirrors New Managers Induction Program.  

Covered: Developing the Business, Planning and Organizing, Coaching and Development. 

Innovating and Improving, Solving Problems, Leadership and Direction. 

Customer Focus, Communicating and Influencing, Managing a Team. 

 
